version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/api/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - db
      - mail

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "13306:3306"

  redis:
    image: redis:7.0-alpine3.17
    volumes:
      - redis-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db-data:
  redis-data:
